version: "3.7"
services:
  tfserving:
    image: tensorflow/serving
    ports:
      - "8501:8501"
    volumes:
      - "/Users/theofpa/Developer/kserve-tutorial/mnist:/models/model"
    command:
      - tensorflow_model_server
      - --port=8500
      - --rest_api_port=8501
      - --model_name=model
      - --model_base_path=/models/model
      - --monitoring_config_file=/models/model/monitoring.conf