apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast
  labels:
    app: feast
spec:
  selector:
    matchLabels:
      app: feast
  template:
    metadata:
      labels:
        app: feast
    spec:
      containers:
      - name: feast
        image: theofpa/kserve-feast
        args: [-c, /mnt, serve, -h, 0.0.0.0]
        ports:
        - containerPort: 6566
---
apiVersion: v1
kind: Service
metadata:
  name: feast
spec:
  selector:
    app: feast
  ports:
    - protocol: TCP
      port: 6566
      targetPort: 6566
      name: http